In [1]:
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import hilbert
import plotly.graph_objects as go

In [2]:
import logging
logging.basicConfig(level=logging.DEBUG)

In [3]:
import di_lib

In [4]:
from di_lib.session import DISession

In [5]:
server_url = 'http://localhost:9990'
# server_url = 'http://localhost:8000'
# project_id = 19636343 # Kazan_test
project_id = 19637517 # test_Geom3
# project_id = 60 # test
# project_id = 3344621 # big_3

token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcl9uYW1lIjoia2F6YW4ifQ.CeFkjtwL0JraAaLjRSHzLwKYRSV95oi2sH_Wrz5VUFI'
s = DISession(project_id, server_url, token)

In [7]:
la = s.list_attributes_3d()
la

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /horizons/3d/list/19637517/ HTTP/1.1" 200 2115


[{'id': 19861107,
  'name': 'new_attr_B6',
  'nx': 581,
  'ny': 430,
  'origin': [13490700.0, 6677430.0],
  'dx': [-25.0, 43.3017],
  'dy': [43.3017, 25.0],
  'ref_data': None,
  'domain': 'D',
  'mode': 'Max',
  'geometry_id': 19637519,
  'geometry_name': 'cube_geom',
  'n_layers': 2}]

In [8]:
lh = s.list_horizons_3d()
lh

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /horizons/3d/list/19637517/ HTTP/1.1" 200 2115


[{'id': 19784583,
  'name': 'B_prop',
  'nx': 581,
  'ny': 430,
  'origin': [13490700.0, 6677430.0],
  'dx': [-25.0, 43.3017],
  'dy': [43.3017, 25.0],
  'ref_data': 19637520,
  'domain': 'T',
  'mode': 'Min',
  'geometry_id': 19637519,
  'geometry_name': 'cube_geom',
  'n_layers': 1},
 {'id': 19858570,
  'name': 'A',
  'nx': 581,
  'ny': 430,
  'origin': [13690700.0, 6877430.0],
  'dx': [-25.0, 43.3017],
  'dy': [43.3017, 25.0],
  'ref_data': 19858567,
  'domain': 'T',
  'mode': 'Min',
  'geometry_id': 19858566,
  'geometry_name': 'cube_geom_200',
  'n_layers': 1},
 {'id': 19858571,
  'name': 'A',
  'nx': 581,
  'ny': 430,
  'origin': [13890700.0, 7077430.0],
  'dx': [-25.0, 43.3017],
  'dy': [43.3017, 25.0],
  'ref_data': 19858569,
  'domain': 'T',
  'mode': 'Min',
  'geometry_id': 19858568,
  'geometry_name': 'cube_geom_400',
  'n_layers': 1},
 {'id': 19841181,
  'name': 'horr_new',
  'nx': 581,
  'ny': 430,
  'origin': [13490700.0, 6677430.0],
  'dx': [-25.0, 43.3017],
  'dy': [43.

In [9]:
hor = s.get_horizon_3d("cube_geom", "B_prop")
# hor = s.get_attribute_3d_writer("auto cube1", "hor_A")
hor

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /horizons/3d/list/19637517/ HTTP/1.1" 200 2115
DEBUG:di_lib.attribute:{'id': 19784583, 'name': 'B_prop', 'nx': 581, 'ny': 430, 'origin': [13490700.0, 6677430.0], 'dx': [-25.0, 43.3017], 'dy': [43.3017, 25.0], 'ref_data': 19637520, 'domain': 'T', 'mode': 'Min', 'geometry_id': 19637519, 'geometry_name': 'cube_geom', 'n_layers': 1}


DIHorizon3D: self.horizon_id=19784583 self.geometry_name='cube_geom' self.name='B_prop'

In [10]:
hor._get_info()

{'geometry_name': 'cube_geom',
 'geometry_id': 19637519,
 'name': 'B_prop',
 'nx': 581,
 'ny': 430,
 'origin': [13490700.0, 6677430.0],
 'dx': [-25.0, 43.3017],
 'dy': [43.3017, 25.0],
 'domain': 'T',
 'id': 19784583,
 'mode': 'Min'}

In [11]:
hdata = hor.get_data()
hdata.shape

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /horizons/3d/data/19637517/19784583/ HTTP/1.1" 200 999328
DEBUG:di_lib.attribute:nx=581, ny=430


(581, 430)

In [13]:
new_hor = s.create_horizon_3d_writer_as_other(hor, "new_hor_B6", mode="Max", domain="D")
new_hor

DEBUG:di_lib.attribute:{'geometry_name': 'cube_geom', 'geometry_id': 19637519, 'name': 'B_prop', 'nx': 581, 'ny': 430, 'origin': [13490700.0, 6677430.0], 'dx': [-25.0, 43.3017], 'dy': [43.3017, 25.0], 'domain': 'D', 'id': 19784583, 'mode': 'Max'}
INFO:di_lib.attribute:hor_out={'name': 'new_hor_B6', 'nx': 581, 'ny': 430, 'origin': [13490700.0, 6677430.0], 'dx': [-25.0, 43.3017], 'dy': [43.3017, 25.0], 'domain': 'D', 'mode': 'Max'}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "POST /horizons/3d/create_empty/19637517/?geometry_id=19637519 HTTP/1.1" 200 191
INFO:di_lib.attribute:Reply: {'id': 19861109, 'name': 'new_hor_B6', 'nx': 581, 'ny': 430, 'origin': [13490700.0, 6677430.0], 'dx': [-25.0, 43.3017], 'dy': [43.3017, 25.0], 'ref_data': None, 'domain': 'D', 'mode': 'Max', 'geometry_id': 19637519}


DIHorizon3D: self.horizon_id=19861109 self.geometry_name='cube_geom' self.name='new_hor_B6'

In [14]:
ar = np.arange(hor.n_i*hor.n_x, dtype=np.float32)
ar.shape=(hor.n_i, hor.n_x)
new_hor.write_data(ar)

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "POST /horizons/3d/update_data/19637517/19861109/ HTTP/1.1" 200 43


In [15]:
new_hor.get_data()

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /horizons/3d/data/19637517/19861109/ HTTP/1.1" 200 999328
DEBUG:di_lib.attribute:nx=581, ny=430


array([[0.00000e+00, 1.00000e+00, 2.00000e+00, ..., 4.27000e+02,
        4.28000e+02, 4.29000e+02],
       [4.30000e+02, 4.31000e+02, 4.32000e+02, ..., 8.57000e+02,
        8.58000e+02, 8.59000e+02],
       [8.60000e+02, 8.61000e+02, 8.62000e+02, ..., 1.28700e+03,
        1.28800e+03, 1.28900e+03],
       ...,
       [2.48540e+05, 2.48541e+05, 2.48542e+05, ..., 2.48967e+05,
        2.48968e+05, 2.48969e+05],
       [2.48970e+05, 2.48971e+05, 2.48972e+05, ..., 2.49397e+05,
        2.49398e+05, 2.49399e+05],
       [2.49400e+05, 2.49401e+05, 2.49402e+05, ..., 2.49827e+05,
        2.49828e+05, 2.49829e+05]], dtype=float32)

In [16]:
s.delete_attribute_by_id(new_hor.horizon_id)

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "DELETE /horizons/3d/delete/19861109/ HTTP/1.1" 200 15


In [17]:
new_attr = s.create_attribute_2d_writer_as_other(hor, "new_attr_B6", mode="Max", domain="D")
new_attr

DEBUG:di_lib.attribute:{'geometry_name': 'cube_geom', 'geometry_id': 19637519, 'name': 'B_prop', 'nx': 581, 'ny': 430, 'origin': [13490700.0, 6677430.0], 'dx': [-25.0, 43.3017], 'dy': [43.3017, 25.0], 'domain': 'D', 'id': 19784583, 'mode': 'Max'}
INFO:di_lib.attribute:hor_out={'name': 'new_attr_B6', 'nx': 581, 'ny': 430, 'origin': [13490700.0, 6677430.0], 'dx': [-25.0, 43.3017], 'dy': [43.3017, 25.0], 'domain': 'D', 'mode': 'Max'}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "POST /horizons/3d/create_empty/19637517/?geometry_id=19637519 HTTP/1.1" 200 192
INFO:di_lib.attribute:Reply: {'id': 19861110, 'name': 'new_attr_B6', 'nx': 581, 'ny': 430, 'origin': [13490700.0, 6677430.0], 'dx': [-25.0, 43.3017], 'dy': [43.3017, 25.0], 'ref_data': None, 'domain': 'D', 'mode': 'Max', 'geometry_id': 19637519}


DIHorizon3D: self.horizon_id=19861110 self.geometry_name='cube_geom' self.name='new_attr_B6'

In [18]:
nlayers = 2
ar = np.arange(nlayers*hor.n_i*hor.n_x, dtype=np.float32)
ar.shape=(nlayers, hor.n_i, hor.n_x)
new_attr.write_data(ar)

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "POST /horizons/3d/update_layered_data/19637517/19861110/ HTTP/1.1" 200 43


In [19]:
ar = new_attr.get_data()
ar.shape

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /horizons/3d/layered_data/19637517/19861110/ HTTP/1.1" 200 1998652
DEBUG:di_lib.attribute:nlayers=2 nx=581, ny=430


(2, 581, 430)

In [20]:
ar[0]

array([[0.00000e+00, 1.00000e+00, 2.00000e+00, ..., 4.27000e+02,
        4.28000e+02, 4.29000e+02],
       [4.30000e+02, 4.31000e+02, 4.32000e+02, ..., 8.57000e+02,
        8.58000e+02, 8.59000e+02],
       [8.60000e+02, 8.61000e+02, 8.62000e+02, ..., 1.28700e+03,
        1.28800e+03, 1.28900e+03],
       ...,
       [2.48540e+05, 2.48541e+05, 2.48542e+05, ..., 2.48967e+05,
        2.48968e+05, 2.48969e+05],
       [2.48970e+05, 2.48971e+05, 2.48972e+05, ..., 2.49397e+05,
        2.49398e+05, 2.49399e+05],
       [2.49400e+05, 2.49401e+05, 2.49402e+05, ..., 2.49827e+05,
        2.49828e+05, 2.49829e+05]], dtype=float32)

In [21]:
s.delete_attribute_by_id(new_attr.horizon_id)

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "DELETE /horizons/3d/delete/19861110/ HTTP/1.1" 200 15


In [22]:
c = s.get_cube('cube_geom', 'cube','Imported')

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /seismic_3d/list/19637517/ HTTP/1.1" 200 38280
DEBUG:di_lib.seismic_cube:{'name': 'cube', 'name2': 'Imported', 'max_inline': 581, 'max_xline': 430, 'nz': 301, 'origin': [13490634.69833729, 6677362.198275862], 'd_inline': [-25.0, 43.30172413793103], 'd_xline': [43.30166270783848, 25.0], 'domain': 'T', 'z_start': 1800.0, 'z_step': 2000.0, 'min_inline': 1, 'min_xline': 1, 'id': 19637520, 'geometry_id': 19637519, 'geometry_name': 'cube_geom'}


In [23]:
attr_as_cube = s.create_attribute_2d_writer_for_cube(c, "attr_as_cube")
attr_as_cube

DEBUG:di_lib.attribute:{'id': None, 'dx': [-25.0, 43.30172413793103], 'dy': [43.30166270783848, 25.0], 'origin': [13490634.69833729, 6677362.198275862], 'nx': 581, 'ny': 430, 'geometry_id': 19637519, 'geometry_name': 'cube_geom', 'domain': 'T', 'mode': None}
INFO:di_lib.attribute:hor_out={'name': 'attr_as_cube', 'nx': 581, 'ny': 430, 'origin': [13490634.69833729, 6677362.198275862], 'dx': [-25.0, 43.30172413793103], 'dy': [43.30166270783848, 25.0], 'domain': 'T', 'mode': None}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "POST /horizons/3d/create_empty/19637517/?geometry_id=19637519 HTTP/1.1" 200 227
INFO:di_lib.attribute:Reply: {'id': 19861111, 'name': 'attr_as_cube', 'nx': 581, 'ny': 430, 'origin': [13490634.69833729, 6677362.198275862], 'dx': [-25.0, 43.30172413793103], 'dy': [43.30166270783848, 25.0], 'ref_data': None, 'domain': 'T', 'mode': None, 'geometry_id': 19637519}


DIHorizon3D: self.horizon_id=19861111 self.geometry_name='cube_geom' self.name='attr_as_cube'

In [24]:
nx = attr_as_cube.n_i
ny = attr_as_cube.n_x
ar = np.arange(2*nx*ny, dtype=np.float32)
ar.shape = (2, nx, ny)
attr_as_cube.write_data(ar)

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "POST /horizons/3d/update_layered_data/19637517/19861111/ HTTP/1.1" 200 43


In [25]:
attr_as_cube1 = s.get_attribute_2d_writer("cube_geom", "attr_as_cube")
attr_as_cube1

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /horizons/3d/list/19637517/ HTTP/1.1" 200 1914
DEBUG:di_lib.attribute:{'id': 19861111, 'name': 'attr_as_cube', 'nx': 581, 'ny': 430, 'origin': [13490634.69833729, 6677362.198275862], 'dx': [-25.0, 43.30172413793103], 'dy': [43.30166270783848, 25.0], 'ref_data': None, 'domain': 'T', 'mode': None, 'geometry_id': 19637519, 'geometry_name': 'cube_geom', 'n_layers': 2}


DIHorizon3D: self.horizon_id=19861111 self.geometry_name='cube_geom' self.name='attr_as_cube'

In [26]:
ar1 = attr_as_cube1.get_data()
ar1

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /horizons/3d/layered_data/19637517/19861111/ HTTP/1.1" 200 1998652
DEBUG:di_lib.attribute:nlayers=2 nx=581, ny=430


array([[[0.00000e+00, 1.00000e+00, 2.00000e+00, ..., 4.27000e+02,
         4.28000e+02, 4.29000e+02],
        [4.30000e+02, 4.31000e+02, 4.32000e+02, ..., 8.57000e+02,
         8.58000e+02, 8.59000e+02],
        [8.60000e+02, 8.61000e+02, 8.62000e+02, ..., 1.28700e+03,
         1.28800e+03, 1.28900e+03],
        ...,
        [2.48540e+05, 2.48541e+05, 2.48542e+05, ..., 2.48967e+05,
         2.48968e+05, 2.48969e+05],
        [2.48970e+05, 2.48971e+05, 2.48972e+05, ..., 2.49397e+05,
         2.49398e+05, 2.49399e+05],
        [2.49400e+05, 2.49401e+05, 2.49402e+05, ..., 2.49827e+05,
         2.49828e+05, 2.49829e+05]],

       [[2.49830e+05, 2.49831e+05, 2.49832e+05, ..., 2.50257e+05,
         2.50258e+05, 2.50259e+05],
        [2.50260e+05, 2.50261e+05, 2.50262e+05, ..., 2.50687e+05,
         2.50688e+05, 2.50689e+05],
        [2.50690e+05, 2.50691e+05, 2.50692e+05, ..., 2.51117e+05,
         2.51118e+05, 2.51119e+05],
        ...,
        [4.98370e+05, 4.98371e+05, 4.98372e+05, ..., 4

In [27]:
s.delete_attribute_by_id(attr_as_cube.horizon_id)

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "DELETE /horizons/3d/delete/19861111/ HTTP/1.1" 200 15
