In [1]:
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import hilbert
import plotly.graph_objects as go
# from icecream import ic

In [2]:
import logging
logging.basicConfig(level=logging.DEBUG)

In [3]:
import di_lib

In [4]:
from di_lib.session import DISession

In [5]:
server_url = 'http://localhost:9990'
# server_url = 'http://94.25.20.6:9990'
# server_url = 'http://localhost:8000'
# project_id = 19636343 # Kazan_test
project_id = 19637517 # test_Geom3
# project_id = 60 # test efr
# project_id = 3344621 # big_3

token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcl9uYW1lIjoia2F6YW4ifQ.CeFkjtwL0JraAaLjRSHzLwKYRSV95oi2sH_Wrz5VUFI'

s = DISession(project_id, server_url, token)

In [6]:
la = s.list_attributes_2d()
la

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /attributes/3d/list/19637517/ HTTP/11" 200 319


[{'id': 19982115,
  'name': 'new_attr',
  'nx': 581,
  'ny': 430,
  'origin': [13490600.0, 6677360.0],
  'dx': [-25.0, 43.3017],
  'dy': [43.3017, 25.0],
  'ref_data': None,
  'domain': 'D',
  'mode': 'Max',
  'geometry_id': 19637519,
  'min_nx': 1,
  'min_ny': 1,
  'geometry_name': 'cube_geom',
  'n_layers': 2,
  'layers_names': ['Horizon', 'Values'],
  'name2': 'attribute 2nd name'}]

In [7]:
lh = s.list_horizons_3d()
lh

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /horizons/3d/list/19637517/ HTTP/11" 200 6187


[{'id': 19960907,
  'name': 'Result_n',
  'nx': 581,
  'ny': 430,
  'origin': [13490600.0, 6677360.0],
  'dx': [-25.0, 43.3017],
  'dy': [43.3017, 25.0],
  'ref_data': None,
  'domain': 'T',
  'mode': 'Min',
  'geometry_id': 19637519,
  'min_nx': 1,
  'min_ny': 1,
  'geometry_name': 'cube_geom',
  'n_layers': 1,
  'layers_names': None},
 {'id': 19912330,
  'name': 'cube_seis_hor1',
  'nx': 870,
  'ny': 1416,
  'origin': [13463000.0, 6548010.0],
  'dx': [1.53081e-15, 25.0],
  'dy': [12.5004, -1.53085e-15],
  'ref_data': 19779113,
  'domain': 'T',
  'mode': 'Min',
  'geometry_id': 19779112,
  'min_nx': 5076,
  'min_ny': 1189,
  'geometry_name': 'gav_geom',
  'n_layers': 1,
  'layers_names': ['string111',
   'string222',
   'string33',
   'string44',
   'string55']},
 {'id': 19902648,
  'name': 'cube_seis_hor1',
  'nx': 581,
  'ny': 430,
  'origin': [13490600.0, 6677360.0],
  'dx': [-25.0, 43.3017],
  'dy': [43.3017, 25.0],
  'ref_data': 19646734,
  'domain': 'T',
  'mode': 'Max',
  'geom

In [8]:
# hor = s.get_horizon_3d("cube_geom", "B_prop")
hor = s.get_horizon_3d_writer("cube_geom", "cube_seis_hor2")
# hor = s.get_attribute_3d_writer("auto cube1", "hor_A")
hor

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /horizons/3d/list/19637517/ HTTP/11" 200 6187
DEBUG:di_lib.attribute:{'id': 19904436, 'name': 'cube_seis_hor2', 'nx': 581, 'ny': 430, 'origin': [13490600.0, 6677360.0], 'dx': [-25.0, 43.3017], 'dy': [43.3017, 25.0], 'ref_data': 19646734, 'domain': 'T', 'mode': 'Max', 'geometry_id': 19637519, 'min_nx': 1, 'min_ny': 1, 'geometry_name': 'cube_geom', 'n_layers': 1, 'layers_names': None}


DIHorizon3D: self.horizon_id=19904436 self.geometry_name='cube_geom' self.name='cube_seis_hor2'

In [9]:
hor._get_info()

{'geometry_name': 'cube_geom',
 'geometry_id': 19637519,
 'name': 'cube_seis_hor2',
 'nx': 581,
 'ny': 430,
 'min_nx': 1,
 'min_ny': 1,
 'origin': [13490600.0, 6677360.0],
 'dx': [-25.0, 43.3017],
 'dy': [43.3017, 25.0],
 'domain': 'T',
 'id': 19904436,
 'mode': 'Max'}

In [10]:
hdata = hor.get_data()
print(hdata.shape)
hdata

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /horizons/3d/data/19637517/19904436/ HTTP/11" 200 999328
DEBUG:di_lib.attribute:nx=581, ny=430


(581, 430)


array([[3.4028235e+38, 3.4028235e+38, 3.4028235e+38, ..., 3.4028235e+38,
        3.4028235e+38, 3.4028235e+38],
       [3.4028235e+38, 3.4028235e+38, 3.4028235e+38, ..., 3.4028235e+38,
        3.4028235e+38, 3.4028235e+38],
       [3.4028235e+38, 3.4028235e+38, 3.4028235e+38, ..., 3.4028235e+38,
        3.4028235e+38, 3.4028235e+38],
       ...,
       [3.4028235e+38, 3.4028235e+38, 3.4028235e+38, ..., 3.4028235e+38,
        3.4028235e+38, 3.4028235e+38],
       [3.4028235e+38, 3.4028235e+38, 3.4028235e+38, ..., 3.4028235e+38,
        3.4028235e+38, 3.4028235e+38],
       [3.4028235e+38, 3.4028235e+38, 3.4028235e+38, ..., 3.4028235e+38,
        3.4028235e+38, 3.4028235e+38]], dtype=float32)

In [11]:
new_attr = s.create_attribute_2d_writer_as_other(hor, "new_attr 1", "attribute 2nd name", domain="D", copy_horizon_data=True)
new_attr

DEBUG:di_lib.attribute:{'geometry_name': 'cube_geom', 'geometry_id': 19637519, 'name': 'cube_seis_hor2', 'nx': 581, 'ny': 430, 'min_nx': 1, 'min_ny': 1, 'origin': [13490600.0, 6677360.0], 'dx': [-25.0, 43.3017], 'dy': [43.3017, 25.0], 'domain': 'D', 'id': 19904436, 'mode': 'Max'}
INFO:di_lib.attribute:hor_out={'name': 'new_attr 1', 'name2': 'attribute 2nd name', 'nx': 581, 'ny': 430, 'min_nx': 1, 'min_ny': 1, 'origin': [13490600.0, 6677360.0], 'dx': [-25.0, 43.3017], 'dy': [43.3017, 25.0], 'domain': 'D', 'mode': 'Max'}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "POST /attributes/3d/create_empty/19637517/?geometry_id=19637519 HTTP/11" 200 319
INFO:di_lib.attribute:Reply: {'id': 19982119, 'name': 'new_attr 1', 'nx': 581, 'ny': 430, 'origin': [13490600.0, 6677360.0], 'dx': [-25.0, 43.3017], 'dy': [43.3017, 25.0], 'ref_data': None, 'domain': 'D', 'mode': 'Max', 'geometry_id': 19637519, 'min_nx': 1, 'min_n

DIAttribute3D: self.horizon_id=19982119 self.geometry_name='cube_geom' self.name='new_attr 1' self.name2='attribute 2nd name'

In [12]:
# new_attr.layers_names = ["T0", "Energy"]
print(new_attr._get_info())
new_attr.layers_names

{'geometry_name': 'cube_geom', 'geometry_id': 19637519, 'name': 'new_attr 1', 'name2': 'attribute 2nd name', 'nx': 581, 'ny': 430, 'min_nx': 1, 'min_ny': 1, 'origin': [13490600.0, 6677360.0], 'dx': [-25.0, 43.3017], 'dy': [43.3017, 25.0], 'domain': 'D', 'id': 19982119, 'mode': 'Max'}


['Horizon', 'Values']

In [13]:
new_attr.get_all_data()

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /attributes/3d/layers_data/19637517/19982119/ HTTP/11" 200 1998652
DEBUG:di_lib.attribute:nlayers=2 nx=581, ny=430


array([[[3.4028235e+38, 3.4028235e+38, 3.4028235e+38, ...,
         3.4028235e+38, 3.4028235e+38, 3.4028235e+38],
        [3.4028235e+38, 3.4028235e+38, 3.4028235e+38, ...,
         3.4028235e+38, 3.4028235e+38, 3.4028235e+38],
        [3.4028235e+38, 3.4028235e+38, 3.4028235e+38, ...,
         3.4028235e+38, 3.4028235e+38, 3.4028235e+38],
        ...,
        [3.4028235e+38, 3.4028235e+38, 3.4028235e+38, ...,
         3.4028235e+38, 3.4028235e+38, 3.4028235e+38],
        [3.4028235e+38, 3.4028235e+38, 3.4028235e+38, ...,
         3.4028235e+38, 3.4028235e+38, 3.4028235e+38],
        [3.4028235e+38, 3.4028235e+38, 3.4028235e+38, ...,
         3.4028235e+38, 3.4028235e+38, 3.4028235e+38]],

       [[          inf,           inf,           inf, ...,
                   inf,           inf,           inf],
        [          inf,           inf,           inf, ...,
                   inf,           inf,           inf],
        [          inf,           inf,           inf, ...,
              

In [14]:
nlayers = 2
ar = np.arange(nlayers*hor.n_i*hor.n_x, dtype=np.float32)
ar.shape=(nlayers, hor.n_i, hor.n_x)
# new_attr.write_horizon_data(ar[0]+200)
new_attr.write_data(ar[1])

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "POST /attributes/3d/update_attribute_data/19637517/19982119/ HTTP/11" 200 43


In [15]:
dt = new_attr.get_all_data()
print(dt.shape)
dt[0] # horizon
dt[1] # attribute data

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /attributes/3d/layers_data/19637517/19982119/ HTTP/11" 200 1998652
DEBUG:di_lib.attribute:nlayers=2 nx=581, ny=430


(2, 581, 430)


array([[249830., 249831., 249832., ..., 250257., 250258., 250259.],
       [250260., 250261., 250262., ..., 250687., 250688., 250689.],
       [250690., 250691., 250692., ..., 251117., 251118., 251119.],
       ...,
       [498370., 498371., 498372., ..., 498797., 498798., 498799.],
       [498800., 498801., 498802., ..., 499227., 499228., 499229.],
       [499230., 499231., 499232., ..., 499657., 499658., 499659.]],
      dtype=float32)

In [16]:
nlayers = 3
ar = np.arange(nlayers*hor.n_i*hor.n_x, dtype=np.float32)
ar.shape=(nlayers, hor.n_i, hor.n_x)
new_attr.write_all_data(ar, ["T0", "Energy", "Rel"])

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "POST /attributes/3d/update_attribute_entire_data/19637517/19982119/?lnm=T0&lnm=Energy&lnm=Rel HTTP/11" 200 43


In [17]:
ar = new_attr.get_data()
print(ar.shape)
ar

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /attributes/3d/data/19637517/19982119/?layer_name=Energy HTTP/11" 200 999328
DEBUG:di_lib.attribute:nx=581, ny=430


(581, 430)


array([[249830., 249831., 249832., ..., 250257., 250258., 250259.],
       [250260., 250261., 250262., ..., 250687., 250688., 250689.],
       [250690., 250691., 250692., ..., 251117., 251118., 251119.],
       ...,
       [498370., 498371., 498372., ..., 498797., 498798., 498799.],
       [498800., 498801., 498802., ..., 499227., 499228., 499229.],
       [499230., 499231., 499232., ..., 499657., 499658., 499659.]],
      dtype=float32)

In [18]:
dt = new_attr.get_all_data()
print(dt.shape)

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /attributes/3d/layers_data/19637517/19982119/ HTTP/11" 200 2997972
DEBUG:di_lib.attribute:nlayers=3 nx=581, ny=430


(3, 581, 430)


In [19]:
new_attr_cp = s.get_attribute_2d_writer(new_attr.geometry_name, new_attr.name, new_attr.name2)

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /attributes/3d/list/19637517/ HTTP/11" 200 640
DEBUG:di_lib.attribute:{'id': 19982119, 'name': 'new_attr 1', 'nx': 581, 'ny': 430, 'origin': [13490600.0, 6677360.0], 'dx': [-25.0, 43.3017], 'dy': [43.3017, 25.0], 'ref_data': None, 'domain': 'D', 'mode': 'Max', 'geometry_id': 19637519, 'min_nx': 1, 'min_ny': 1, 'geometry_name': 'cube_geom', 'n_layers': 3, 'layers_names': ['T0', 'Energy', 'Rel'], 'name2': 'attribute 2nd name'}


In [20]:
new_attr_cp.layers_names

['T0', 'Energy', 'Rel']

In [21]:
# Not working any more. The only way to change layers names is via the write_all_data() method
new_attr_cp.layers_names = ['T0', 'Amplitude'] 

AttributeError: property 'layers_names' of 'DIAttribute2D' object has no setter

In [22]:
new_attr_cp.layers_names

['T0', 'Energy', 'Rel']

In [23]:
s.delete_attribute_by_id(new_attr.horizon_id)

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "DELETE /attributes/3d/delete/19982119/ HTTP/11" 200 15


In [24]:
c = s.get_cube('cube_geom', 'cube','Imported')

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /seismic_3d/list/19637517/ HTTP/11" 200 23249
DEBUG:di_lib.seismic_cube:{'name': 'cube', 'name2': 'Imported', 'max_inline': 581, 'max_xline': 430, 'nz': 301, 'origin': [13490634.69833729, 6677362.198275862], 'd_inline': [-25.0, 43.30172413793103], 'd_xline': [43.30166270783848, 25.0], 'domain': 'T', 'z_start': 1800.0, 'z_step': 2000.0, 'min_inline': 1, 'min_xline': 1, 'id': 19637520, 'geometry_id': 19637519, 'geometry_name': 'cube_geom'}


In [25]:
attr_as_cube = s.create_attribute_2d_writer_for_cube(c, "attr_as_cube", "attribute 2nd name")
attr_as_cube

DEBUG:di_lib.attribute:{'id': None, 'dx': [-25.0, 43.30172413793103], 'dy': [43.30166270783848, 25.0], 'origin': [13490634.69833729, 6677362.198275862], 'nx': 581, 'ny': 430, 'geometry_id': 19637519, 'geometry_name': 'cube_geom', 'domain': 'T', 'mode': None, 'min_nx': 1, 'min_ny': 1}
INFO:di_lib.attribute:hor_out={'name': 'attr_as_cube', 'name2': 'attribute 2nd name', 'nx': 581, 'ny': 430, 'min_nx': 1, 'min_ny': 1, 'origin': [13490634.69833729, 6677362.198275862], 'dx': [-25.0, 43.30172413793103], 'dy': [43.30166270783848, 25.0], 'domain': 'T', 'mode': None}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "POST /attributes/3d/create_empty/19637517/?geometry_id=19637519 HTTP/11" 200 355
INFO:di_lib.attribute:Reply: {'id': 19982120, 'name': 'attr_as_cube', 'nx': 581, 'ny': 430, 'origin': [13490634.69833729, 6677362.198275862], 'dx': [-25.0, 43.30172413793103], 'dy': [43.30166270783848, 25.0], 'ref_data': Non

DIAttribute3D: self.horizon_id=19982120 self.geometry_name='cube_geom' self.name='attr_as_cube' self.name2='attribute 2nd name'

In [26]:
nx = attr_as_cube.n_i
ny = attr_as_cube.n_x
ar = np.arange(2*nx*ny, dtype=np.float32)
ar.shape = (2, nx, ny)
attr_as_cube.write_horizon_data(ar[0])
attr_as_cube.write_data(ar[1])

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "POST /attributes/3d/update_horizon_data/19637517/19982120/ HTTP/11" 200 43
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "POST /attributes/3d/update_attribute_data/19637517/19982120/ HTTP/11" 200 43


In [27]:
attr_as_cube1 = s.get_attribute_2d_writer("cube_geom", "attr_as_cube", "attribute 2nd name")
attr_as_cube1

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /attributes/3d/list/19637517/ HTTP/11" 200 675
DEBUG:di_lib.attribute:{'id': 19982120, 'name': 'attr_as_cube', 'nx': 581, 'ny': 430, 'origin': [13490634.69833729, 6677362.198275862], 'dx': [-25.0, 43.30172413793103], 'dy': [43.30166270783848, 25.0], 'ref_data': None, 'domain': 'T', 'mode': None, 'geometry_id': 19637519, 'min_nx': 1, 'min_ny': 1, 'geometry_name': 'cube_geom', 'n_layers': 2, 'layers_names': ['Horizon', 'Values'], 'name2': 'attribute 2nd name'}


DIAttribute3D: self.horizon_id=19982120 self.geometry_name='cube_geom' self.name='attr_as_cube' self.name2='attribute 2nd name'

In [28]:
ar1 = attr_as_cube1.get_data()
ar1

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "GET /attributes/3d/data/19637517/19982120/?layer_name=Values HTTP/11" 200 999328
DEBUG:di_lib.attribute:nx=581, ny=430


array([[249830., 249831., 249832., ..., 250257., 250258., 250259.],
       [250260., 250261., 250262., ..., 250687., 250688., 250689.],
       [250690., 250691., 250692., ..., 251117., 251118., 251119.],
       ...,
       [498370., 498371., 498372., ..., 498797., 498798., 498799.],
       [498800., 498801., 498802., ..., 499227., 499228., 499229.],
       [499230., 499231., 499232., ..., 499657., 499658., 499659.]],
      dtype=float32)

In [29]:
s.delete_attribute_by_id(attr_as_cube.horizon_id)

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9990
DEBUG:urllib3.connectionpool:http://localhost:9990 "DELETE /attributes/3d/delete/19982120/ HTTP/11" 200 15
